version: "3"

services:
  dev:
    command: ash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"
    build:
      dockerfile: Dockerfile
      context: docker/
    ports:
    - "8080:8080"
    volumes:
    - "./app:/home"
