version: "3"

services:
  dev:
    command: python3 manage.py runserver 0.0.0.0:8080 
    build:
      dockerfile: Dockerfile
      context: docker/
    ports:
    - "8080:8080"
    volumes:
    - "./app:/home"
