# Generated by Django 2.2.2 on 2019-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoTransacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('contador', models.CharField(max_length=150)),
                ('tipo_funcao', models.CharField(choices=[('EE', 'EE'), ('CE', 'CE'), ('SE', 'SE')], max_length=10)),
                ('complexidade', models.CharField(choices=[('baixa', 'baixa'), ('media', 'media'), ('alta', 'alta')], max_length=40)),
                ('qtd_alr', models.IntegerField()),
                ('qtd_der', models.IntegerField()),
                ('pontos_de_funcao', models.IntegerField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
